// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbppzntxxgukugtkojcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNicHB6bnR4eGd1a3VndGtvamN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEzMzcyNTcsImV4cCI6MjA4NjkxMzI1N30.pVJs_S4w_TXCSQ3-p_Y_dNg3H05ZMRp2-YEzlFUEOh8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});